env:
  DEMO_HOST: httpbin.org
  DEMO_PATH: anything/env
  DEMO_USER: demo-user
  DEMO_PASS: demo-pass
  DEMO_MSG: "hello-env"
routes:
  - name: httpbin-env
    type: http
    url: https://${DEMO_HOST}/${DEMO_PATH}
    method: POST
    headers:
      X-Demo-Source: ${DEMO_MSG}
    basic_auth:
      username: ${DEMO_USER}
      password: ${DEMO_PASS}
    json: payloads/env_payload.json
    max_response_chars: 512
    description: "Пример использования env и подстановок ${VAR}."
